//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int Masp { get; set; }
        public string tenSanPham { get; set; }
        public decimal gia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string danhMuc { get; set; }
    }
}
