//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        
        public DonHang()
        {
           
        }
    
        public int MaDh { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string TenNcc { get; set; }
        public string TenNv { get; set; }
    }
}
