//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
      
        public HoaDon()
        {
           
        }
    
        public int Mahd { get; set; }
        public Nullable<System.DateTime> ngayghi { get; set; }
        public string tenNhanVien { get; set; }
        public string tenKhach { get; set; }
    
      
    }
}
