//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
       
        public NhaCungCap()
        {
            
        }
    
        public int MaNhaCungCap { get; set; }
        public string TenNhaCungCap { get; set; }
        public string DiaCHi { get; set; }
        public string SDT { get; set; }
    
       
    }
}
