//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        
        public NhanVien()
        {
            
        }
    
        public int MaNv { get; set; }
        public string Hoten { get; set; }
        public Nullable<System.DateTime> NgayVaolam { get; set; }
        public string SDT { get; set; }
    
       
    }
}
