//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
     //   [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
          //  this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
          //  this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
          //  this.ChiTietHoaDons1 = new HashSet<ChiTietHoaDon>();
        }
    
        public int Masp { get; set; }
        public string Tensp { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string DonViTinh { get; set; }
        public string TenDM { get; set; }

        public Nullable<int> SoLuong { get; set; }    
    
      //  [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
       // public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
       // [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
       // public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
       // [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
       // public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons1 { get; set; }
        //public virtual DanhMucHang DanhMucHang { get; set; }
    }
}
